# Generated by Django 4.1 on 2022-08-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
